import ReduxProvider from "@/redux/provider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ProtectedRoute from "./protectedRoutes";

const poppins = Poppins({ weight : ["100","200","300","400","500","600","700","800","900"],subsets : ["latin"]});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProvider>
          <ProtectedRoute>
            {children}
          </ProtectedRoute>
        </ReduxProvider>
      </body>
    </html>
  );
}
